#!/usr/bin/env python3
"""
Compute abundance and biovolume for PIScO results.

Usage:
  python calc_abundance_biovolume_pisco.py /path/to/results_root
    python calc_abundance_biovolume_pisco.py /path/to/results_root --output-dir /path/to/output

The script expects results generated by process_pisco_profiles.py:
- Each profile output contains EcoTaxa/*.tsv and settings.csv
- settings.csv provides mask_radius and the original image source directory
"""

import argparse
import math
import os
import re
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

MICRONS_PER_PIXEL = 22.5
DEPTH_MM = 500

DEFAULT_DEPTH_BINS = [0, 100, 500, 1000, 2000, 4000, 10000]
DEFAULT_DEPTH_BIN_MAX = 10000

KNOWN_CRUISES = [
    "HE570",
    "M181",
    "SO298",
    "MSM126",
    "M202",
    "SO308",
    "benchmark_v3",
]

CRUISE_PRESSURE_UNITS = {
    "M181": "bar",
}


def detect_cruise_from_text(text):
    text_upper = text.upper()
    for cruise in KNOWN_CRUISES:
        if cruise.upper() in text_upper:
            return cruise
    return None


def get_pressure_unit(cruise_name):
    return CRUISE_PRESSURE_UNITS.get(cruise_name, "dbar")

def parse_depth_bins(depth_bins_str):
    if not depth_bins_str:
        return DEFAULT_DEPTH_BINS

    try:
        bins = [float(x.strip()) for x in depth_bins_str.split(",") if x.strip() != ""]
    except ValueError as exc:
        raise ValueError("Depth bins must be a comma-separated list of numbers.") from exc

    if len(bins) < 2:
        raise ValueError("Depth bins must contain at least two values.")
    if any(b >= a for a, b in zip(bins[1:], bins[:-1])):
        raise ValueError("Depth bins must be strictly increasing.")

    return bins


def build_even_bins(step_dbar, max_depth):
    if step_dbar <= 0:
        raise ValueError("Depth bin step must be > 0.")
    if max_depth <= 0:
        raise ValueError("Depth bin max must be > 0.")

    edges = [0.0]
    current = 0.0
    while current < max_depth:
        current = current + step_dbar
        if current > max_depth:
            current = max_depth
        edges.append(current)

    if len(edges) < 2:
        raise ValueError("Even bins must contain at least two edges.")

    return edges

def read_settings(profile_output_dir):
    settings_path = Path(profile_output_dir) / "settings.csv"
    if not settings_path.exists():
        return None, None

    try:
        df = pd.read_csv(settings_path)
    except Exception:
        return None, None

    if "Field Name" not in df.columns or "Value" not in df.columns:
        return None, None

    settings = dict(zip(df["Field Name"], df["Value"]))
    mask_radius = settings.get("mask_radius")
    data_source = settings.get("data source")

    try:
        mask_radius = float(mask_radius) if mask_radius is not None else None
    except Exception:
        mask_radius = None

    return mask_radius, data_source


def find_profile_output_dirs(results_root):
    results_root = Path(results_root)
    if (results_root / "EcoTaxa").exists():
        return [results_root]

    profile_dirs = []
    for item in results_root.iterdir():
        if not item.is_dir():
            continue

        if (item / "EcoTaxa").exists():
            profile_dirs.append(item)
            continue

        for child in item.iterdir():
            if child.is_dir() and (child / "EcoTaxa").exists():
                profile_dirs.append(child)

    return sorted(profile_dirs)


def get_profile_name(profile_output_dir):
    profile_output_dir = Path(profile_output_dir)
    if profile_output_dir.name.endswith("_Results") and profile_output_dir.parent.name:
        return profile_output_dir.parent.name
    return profile_output_dir.name


def find_ecotaxa_tsv(profile_output_dir):
    ecotaxa_dir = Path(profile_output_dir) / "EcoTaxa"
    if not ecotaxa_dir.exists():
        return None

    tsvs = list(ecotaxa_dir.glob("*_ecotaxa.tsv"))
    if tsvs:
        return tsvs[0]

    # Fallback: any TSV in EcoTaxa
    tsvs = list(ecotaxa_dir.glob("*.tsv"))
    return tsvs[0] if tsvs else None


def find_image_dir(data_source):
    if not data_source:
        return None

    data_source = Path(data_source)
    if data_source.exists() and data_source.is_dir():
        if list(data_source.glob("*.png")):
            return data_source

        # If passed path is a parent folder, try to find a child with images
        for child in data_source.iterdir():
            if child.is_dir():
                if list(child.glob("*.png")):
                    return child
    return None


def suggest_depth_bin_max_from_profiles(profile_dirs, bin_step, fallback=DEFAULT_DEPTH_BIN_MAX):
    max_pressure = None
    for profile_dir in profile_dirs:
        _, data_source = read_settings(profile_dir)
        image_dir = find_image_dir(data_source)
        if image_dir is None:
            continue

        for image_file in Path(image_dir).glob("*.png"):
            pressure_dbar = extract_pressure_dbar_from_filename(image_file.name)
            if pressure_dbar is None:
                continue
            if max_pressure is None or pressure_dbar > max_pressure:
                max_pressure = pressure_dbar

    if max_pressure is None:
        return fallback

    if bin_step and bin_step > 0:
        return math.ceil(max_pressure / bin_step) * bin_step

    return math.ceil(max_pressure / 100.0) * 100.0


def extract_pressure_dbar_from_filename(filename):
    name = filename.lower()

    match = re.search(r"(\d+(?:\.\d+)?)dbar", name)
    if match:
        return float(match.group(1))

    match = re.search(r"(\d+(?:\.\d+)?)bar", name)
    if match:
        return float(match.group(1)) * 10.0

    match = re.search(r"(\d+(?:\.\d+)?)m", name)
    if match:
        return float(match.group(1))

    return None


def calculate_volume(mask_radius_pixels):
    radius_microns = mask_radius_pixels * MICRONS_PER_PIXEL
    radius_mm = radius_microns / 1000.0
    volume_mm3 = np.pi * (radius_mm ** 2) * DEPTH_MM
    volume_liters = volume_mm3 / 1_000_000.0
    return volume_liters


def load_ecotaxa_df(tsv_path):
    df = pd.read_csv(tsv_path, sep="\t", skiprows=[1], low_memory=False)

    if "object_pressure" not in df.columns:
        df = pd.read_csv(tsv_path, sep="\t", low_memory=False)

    if "object_pressure" in df.columns and not df.empty:
        first_val = str(df["object_pressure"].iloc[0])
        if first_val in ("float", "integer", "string", "datetime"):
            df = df.iloc[1:].reset_index(drop=True)

    return df


def process_profile(
    profile_output_dir,
    depth_bin_edges=DEFAULT_DEPTH_BINS,
):
    empty_counts = pd.DataFrame()
    empty_volumes = pd.DataFrame()
    empty_raw = pd.DataFrame()

    profile_name = get_profile_name(profile_output_dir)
    mask_radius, data_source = read_settings(profile_output_dir)

    cruise_from_path = detect_cruise_from_text(profile_name)
    cruise_from_source = detect_cruise_from_text(data_source or "")
    cruise = cruise_from_path or cruise_from_source or "UNKNOWN"
    pressure_unit = get_pressure_unit(cruise)

    if mask_radius is None:
        print(f"[WARN] Missing mask_radius for {profile_name}")
        return empty_counts, empty_volumes, empty_raw

    image_dir = find_image_dir(data_source)
    if image_dir is None:
        print(f"[WARN] Missing image directory for {profile_name}")
        return empty_counts, empty_volumes, empty_raw

    tsv_path = find_ecotaxa_tsv(profile_output_dir)
    if tsv_path is None:
        print(f"[WARN] Missing EcoTaxa TSV for {profile_name}")
        return empty_counts, empty_volumes, empty_raw

    print(f"Processing {profile_name} (cruise={cruise}, pressure_unit={pressure_unit})")
    volume_per_image = calculate_volume(mask_radius)

    image_files = list(Path(image_dir).glob("*.png"))
    if not image_files:
        print(f"[WARN] No PNG images found in {image_dir}")
        return empty_counts, empty_volumes, empty_raw

    depth_bin_labels = [
        f"{depth_bin_edges[i]}-{depth_bin_edges[i + 1]}m"
        for i in range(len(depth_bin_edges) - 1)
    ]

    volumes_by_depth_bin = defaultdict(float)
    images_by_depth_bin = defaultdict(int)
    for image_file in image_files:
        pressure_dbar = extract_pressure_dbar_from_filename(image_file.name)
        if pressure_dbar is None:
            continue

        bin_idx = pd.cut(
            [pressure_dbar],
            bins=depth_bin_edges,
            labels=False,
            include_lowest=True,
            right=False,
        )[0]

        if not pd.isna(bin_idx):
            depth_label = depth_bin_labels[int(bin_idx)]
            volumes_by_depth_bin[depth_label] += volume_per_image
            images_by_depth_bin[depth_label] += 1

    volume_records = []
    for depth_label, volume in volumes_by_depth_bin.items():
        start, end = depth_label.replace("m", "").split("-")
        volume_records.append(
            {
                "profile": profile_name,
                "cruise": cruise,
                "depth_bin_start_dbar": float(start),
                "depth_bin_end_dbar": float(end),
                "depth_bin_label": depth_label,
                "sampled_volume_L": volume,
                "image_count": images_by_depth_bin.get(depth_label, 0),
                "volume_per_image_L": volume_per_image,
            }
        )

    volume_df = pd.DataFrame(
        volume_records,
        columns=[
            "profile",
            "cruise",
            "depth_bin_start_dbar",
            "depth_bin_end_dbar",
            "depth_bin_label",
            "sampled_volume_L",
            "image_count",
            "volume_per_image_L",
        ],
    )
    if not volume_df.empty:
        volume_df = volume_df.sort_values("depth_bin_start_dbar")

    df = load_ecotaxa_df(tsv_path)
    if "object_pressure" not in df.columns or "object_annotation_category" not in df.columns:
        print(f"[WARN] Missing required columns in {tsv_path}")
        return empty_counts, volume_df, df

    df["object_pressure"] = pd.to_numeric(df["object_pressure"], errors="coerce")
    df = df.dropna(subset=["object_pressure"])

    if pressure_unit == "bar":
        df["pressure_dbar"] = df["object_pressure"] * 10.0
    else:
        df["pressure_dbar"] = df["object_pressure"]

    if "object_esd" in df.columns:
        df["object_esd"] = pd.to_numeric(df["object_esd"], errors="coerce")
        esd_mm = df["object_esd"] / 1000.0
        df["biovolume_mm3"] = (np.pi / 6.0) * (esd_mm ** 3)
    else:
        df["biovolume_mm3"] = 0.0

    df["depth_bin"] = pd.cut(
        df["pressure_dbar"],
        bins=depth_bin_edges,
        labels=depth_bin_labels,
        include_lowest=True,
        right=False,
    )

    counts = (
        df.groupby(["depth_bin", "object_annotation_category"], observed=True)
        .agg(
            biovolume_mm3=("biovolume_mm3", "sum"),
            count=("object_annotation_category", "size"),
            mean_esd=("object_esd", "mean"),
        )
        .reset_index()
    )

    counts["depth_bin"] = counts["depth_bin"].astype(str)
    counts["sampled_volume_L"] = counts["depth_bin"].map(volumes_by_depth_bin)
    counts = counts.dropna(subset=["sampled_volume_L"])
    counts = counts[counts["sampled_volume_L"] > 0]

    counts[["depth_bin_start_dbar", "depth_bin_end_dbar"]] = (
        counts["depth_bin"].str.replace("m", "").str.split("-", expand=True).astype(float)
    )

    counts["profile"] = profile_name
    counts["cruise"] = cruise
    counts["concentration_per_L"] = counts["count"] / counts["sampled_volume_L"]
    counts["biovolume_mm3_per_L"] = counts["biovolume_mm3"] / counts["sampled_volume_L"]

    counts = counts[
        [
            "profile",
            "cruise",
            "depth_bin_start_dbar",
            "depth_bin_end_dbar",
            "depth_bin",
            "object_annotation_category",
            "count",
            "mean_esd",
            "biovolume_mm3",
            "sampled_volume_L",
            "concentration_per_L",
            "biovolume_mm3_per_L",
        ]
    ]

    return counts, volume_df, df


def build_plot_bins_from_df(df, step_dbar):
    max_depth = pd.to_numeric(df["depth_bin_end_dbar"], errors="coerce").max()
    if pd.isna(max_depth) or max_depth <= 0:
        return None
    return build_even_bins(step_dbar, max_depth)


def make_profile_plot(df, raw_df, out_path, plot_bin_step):
    required_cols = {
        "depth_bin_start_dbar",
        "depth_bin_end_dbar",
        "sampled_volume_L",
        "object_annotation_category",
        "count",
        "biovolume_mm3",
    }
    if not required_cols.issubset(df.columns):
        print(f"[WARN] Missing columns for plotting: {out_path}")
        return

    plot_bins = build_plot_bins_from_df(df, plot_bin_step)
    if not plot_bins:
        print(f"[WARN] Could not build plot bins: {out_path}")
        return

    volumes = (
        df[["depth_bin_start_dbar", "depth_bin_end_dbar", "sampled_volume_L"]]
        .dropna()
        .drop_duplicates()
    )
    volumes["depth_bin_coarse"] = pd.cut(
        pd.to_numeric(volumes["depth_bin_start_dbar"], errors="coerce"),
        bins=plot_bins,
        include_lowest=True,
        right=False,
    )
    volume_by_coarse = (
        volumes.groupby("depth_bin_coarse", observed=True)["sampled_volume_L"]
        .sum()
        .reset_index()
    )

    counts = df[
        [
            "depth_bin_start_dbar",
            "object_annotation_category",
            "count",
            "biovolume_mm3",
        ]
    ].copy()
    counts["depth_bin_coarse"] = pd.cut(
        pd.to_numeric(counts["depth_bin_start_dbar"], errors="coerce"),
        bins=plot_bins,
        include_lowest=True,
        right=False,
    )

    counts = (
        counts.groupby(["depth_bin_coarse", "object_annotation_category"], observed=True)
        .agg(
            count=("count", "sum"),
            biovolume_mm3=("biovolume_mm3", "sum"),
        )
        .reset_index()
    )
    counts = counts.merge(volume_by_coarse, on="depth_bin_coarse", how="left")
    counts = counts.dropna(subset=["sampled_volume_L"])
    counts = counts[counts["sampled_volume_L"] > 0]
    counts["concentration_per_L"] = counts["count"] / counts["sampled_volume_L"]
    counts["biovolume_mm3_per_L"] = counts["biovolume_mm3"] / counts["sampled_volume_L"]

    if counts.empty:
        print(f"[WARN] No data to plot: {out_path}")
        return

    depths = counts["depth_bin_coarse"].cat.categories
    depth_mids = [0.5 * (interval.left + interval.right) for interval in depths]
    depth_map = {interval: mid for interval, mid in zip(depths, depth_mids)}
    counts["depth_mid"] = counts["depth_bin_coarse"].map(depth_map)

    mean_esd_by_coarse = (
        raw_df.dropna(subset=["object_esd"])
        .assign(
            depth_bin_coarse=pd.cut(
                pd.to_numeric(raw_df["pressure_dbar"], errors="coerce"),
                bins=plot_bins,
                include_lowest=True,
                right=False,
            )
        )
        .groupby(["depth_bin_coarse", "object_annotation_category"], observed=True)
        .agg(mean_esd=("object_esd", "mean"))
        .reset_index()
    )
    counts = counts.merge(
        mean_esd_by_coarse,
        on=["depth_bin_coarse", "object_annotation_category"],
        how="left",
    )

    classes = sorted(counts["object_annotation_category"].dropna().unique())
    if not classes:
        print(f"[WARN] No classes to plot: {out_path}")
        return

    abundance_vals = counts["concentration_per_L"]
    abundance_vals = abundance_vals[abundance_vals > 0]
    biovolume_vals = counts["biovolume_mm3_per_L"]
    biovolume_vals = biovolume_vals[biovolume_vals > 0]
    esd_vals = counts["mean_esd"]
    esd_vals = esd_vals[esd_vals > 0]

    abundance_min = abundance_vals.min() if not abundance_vals.empty else None
    abundance_max = abundance_vals.max() if not abundance_vals.empty else None
    biovolume_min = biovolume_vals.min() if not biovolume_vals.empty else None
    biovolume_max = biovolume_vals.max() if not biovolume_vals.empty else None
    esd_min = esd_vals.min() if not esd_vals.empty else None
    esd_max = esd_vals.max() if not esd_vals.empty else None

    if abundance_min is not None and abundance_max is not None:
        if abundance_min == abundance_max:
            abundance_min *= 0.5
            abundance_max *= 2.0
        else:
            abundance_min *= 0.9
            abundance_max *= 1.1

    if biovolume_min is not None and biovolume_max is not None:
        if biovolume_min == biovolume_max:
            biovolume_min *= 0.5
            biovolume_max *= 2.0
        else:
            biovolume_min *= 0.9
            biovolume_max *= 1.1

    if esd_min is not None and esd_max is not None:
        if esd_min == esd_max:
            esd_min *= 0.5
            esd_max *= 2.0
        else:
            esd_min *= 0.9
            esd_max *= 1.1

    ncols = 3
    nrows = int(math.ceil(len(classes) / ncols))
    fig, axes = plt.subplots(
        nrows=nrows,
        ncols=ncols,
        figsize=(5.0 * ncols, 7.0 * nrows),
        sharey=True,
    )
    axes = np.atleast_1d(axes).flatten()

    profile_name = df["profile"].dropna().iloc[0] if "profile" in df.columns else "profile"

    for ax, cls in zip(axes, classes):
        cls_data = counts[counts["object_annotation_category"] == cls]
        cls_data = cls_data.sort_values("depth_mid")

        y_min = cls_data["depth_mid"].min()
        y_max = cls_data["depth_mid"].max()

        abundance = cls_data["concentration_per_L"]
        abundance_mask = abundance > 0
        line1 = None
        if abundance_mask.any():
            line1, = ax.plot(
                abundance[abundance_mask],
                cls_data["depth_mid"][abundance_mask],
                color="tab:blue",
                label="abundance/L",
            )
        ax.set_title(str(cls))
        ax.set_xlabel("abundance per L")
        ax.xaxis.label.set_color("tab:blue")
        ax.tick_params(axis="x", labelcolor="tab:blue")
        for spine in ["top", "right", "left"]:
            ax.spines[spine].set_visible(True)
        ax.spines["bottom"].set_color("tab:blue")
        ax.spines["left"].set_color("black")
        if pd.notna(y_min) and pd.notna(y_max) and y_min == y_max:
            pad = max(1.0, 0.05 * y_max)
            ax.set_ylim(y_max + pad, y_min - pad)
        else:
            ax.set_ylim(y_max, y_min)
        ax.grid(True, alpha=0.3)

        ax2 = ax.twiny()
        biovolume = cls_data["biovolume_mm3_per_L"]
        biovolume_mask = biovolume > 0
        line2 = None
        if biovolume_mask.any():
            line2, = ax2.plot(
                biovolume[biovolume_mask],
                cls_data["depth_mid"][biovolume_mask],
                color="tab:orange",
                label="biovolume mm3/L",
            )
        ax2.set_xlabel("biovolume mm3 per L")
        ax2.xaxis.label.set_color("tab:orange")
        ax2.tick_params(axis="x", labelcolor="tab:orange")
        ax2.spines["top"].set_color("tab:orange")
        ax2.set_ylim(ax.get_ylim())

        ax3 = ax.twiny()
        ax3.spines["bottom"].set_position(("axes", -0.15))
        ax3.xaxis.set_label_position("bottom")
        ax3.xaxis.tick_bottom()
        ax3.spines["top"].set_visible(False)
        ax3.spines["bottom"].set_visible(True)
        esd = cls_data["mean_esd"]
        esd_mask = esd > 0
        line3 = None
        if esd_mask.any():
            line3, = ax3.plot(
                esd[esd_mask],
                cls_data["depth_mid"][esd_mask],
                color="tab:green",
                label="mean ESD (µm)",
            )
        ax3.set_xlabel("mean ESD (µm)")
        ax3.xaxis.label.set_color("tab:green")
        ax3.tick_params(axis="x", labelcolor="tab:green")
        ax3.spines["bottom"].set_color("tab:green")
        ax3.set_ylim(ax.get_ylim())

        ax.set_xscale("log")
        ax2.set_xscale("log")
        ax3.set_xscale("log")

        if abundance_min is not None and abundance_max is not None:
            ax.set_xlim(abundance_min, abundance_max)
        if biovolume_min is not None and biovolume_max is not None:
            ax2.set_xlim(biovolume_min, biovolume_max)
        if esd_min is not None and esd_max is not None:
            ax3.set_xlim(esd_min, esd_max)

        if "legend_handles" not in locals() and line1 is not None and line2 is not None and line3 is not None:
            legend_handles = (line1, line2, line3)

    for ax in axes[len(classes) :]:
        ax.axis("off")

    fig.suptitle(f"{profile_name}: abundance + biovolume vs depth")
    if "legend_handles" in locals():
        fig.legend(
            legend_handles,
            ["abundance/L", "biovolume mm3/L", "mean ESD (µm)"],
            loc="upper right",
            frameon=False,
        )
    fig.subplots_adjust(left=0.1, right=0.9, top=0.93, bottom=0.12, hspace=0.6, wspace=0.3)
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def plot_cruise_summary(summary_df, profile_order, out_dir):
    if summary_df.empty:
        return

    cruises = summary_df["cruise"].dropna().unique()
    classes = sorted(
        cls
        for cls in summary_df["object_annotation_category"].dropna().unique()
        if str(cls).lower() != "not-living"
    )
    if not classes:
        return

    cmap = plt.get_cmap("tab20")
    colors = [cmap(i % cmap.N) for i in range(len(classes))]
    class_colors = dict(zip(classes, colors))

    for cruise in cruises:
        cruise_df = summary_df[summary_df["cruise"] == cruise]
        profiles = [p for p in profile_order if p in cruise_df["profile"].unique()]
        if not profiles:
            profiles = sorted(cruise_df["profile"].unique())

        profile_labels = {
            profile: (profile.split("_")[1] if "_" in profile else profile)
            for profile in profiles
        }

        for metric, label in (
            ("count_per_L", "Abundance per L"),
            ("biovolume_mm3_per_L", "Biovolume per L (mm3/L)"),
        ):
            pivot = (
                cruise_df.pivot_table(
                    index="profile",
                    columns="object_annotation_category",
                    values=metric,
                    aggfunc="sum",
                    fill_value=0.0,
                )
                .reindex(index=profiles)
                .reindex(columns=classes)
            )

            if pivot.empty:
                continue

            fig_width = max(8.0, 0.4 * len(profiles))
            fig, ax = plt.subplots(figsize=(fig_width, 5.0))
            bottom = np.zeros(len(pivot))

            for cls in classes:
                values = pivot[cls].values
                ax.bar(
                    pivot.index,
                    values,
                    bottom=bottom,
                    color=class_colors.get(cls),
                    label=str(cls),
                )
                bottom += values

            ax.set_ylabel(label)
            ax.set_title(f"{cruise}: {label} by profile")
            ax.set_xticks(range(len(pivot.index)))
            ax.set_xticklabels([profile_labels[p] for p in pivot.index], rotation=90)
            ax.legend(title="Class", bbox_to_anchor=(1.02, 1), loc="upper left")
            fig.tight_layout()

            out_path = Path(out_dir) / f"{cruise}_{metric}_stacked.png"
            fig.savefig(out_path, dpi=150)
            plt.close(fig)


def main():
    parser = argparse.ArgumentParser(
        description="Calculate abundance and biovolume from process_pisco_profiles outputs."
    )
    parser.add_argument(
        "results_root",
        help="Path to a results folder (single profile) or a parent folder of profiles.",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Folder where all CSV and plot outputs are written. Defaults to results_root.",
    )
    parser.add_argument(
    "--depth-bins",
    default=None,
    help="Comma-separated bin edges in dbar, e.g. 0,50,100,200,500,1000",
    )
    parser.add_argument(
        "--depth-bin-step",
        type=float,
        default=None,
        help="Evenly spaced bin width in dbar, e.g. 5 or 10.",
    )
    parser.add_argument(
        "--depth-bin-max",
        type=float,
        default=None,
        help="Maximum depth in dbar for evenly spaced bins.",
    )

    args = parser.parse_args()

    if args.depth_bins and args.depth_bin_step:
        parser.error("Use either --depth-bins or --depth-bin-step, not both.")

    profile_dirs = find_profile_output_dirs(args.results_root)
    if not profile_dirs:
        print("No profile outputs found.")
        return

    if args.depth_bin_step:
        if args.depth_bin_max is None:
            depth_bin_max = suggest_depth_bin_max_from_profiles(
                profile_dirs, args.depth_bin_step, fallback=DEFAULT_DEPTH_BIN_MAX
            )
        else:
            depth_bin_max = args.depth_bin_max
        depth_bin_edges = build_even_bins(args.depth_bin_step, depth_bin_max)
    else:
        depth_bin_edges = parse_depth_bins(args.depth_bins)

    output_dir = Path(args.output_dir) if args.output_dir else Path(args.results_root)
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"Writing outputs to: {output_dir}")

    summary_records = []
    profile_order = [get_profile_name(p) for p in profile_dirs]

    for profile_dir in profile_dirs:
        counts, volumes, raw_df = process_profile(profile_dir, depth_bin_edges=depth_bin_edges)
        profile_dir = Path(profile_dir)
        profile_name = get_profile_name(profile_dir)

        if counts.empty and volumes.empty:
            print(f"No counts generated for {profile_dir.name}.")
            continue

        if not volumes.empty:
            volumes = volumes.rename(columns={"depth_bin_label": "depth_bin"})

        if counts.empty:
            combined = volumes
        elif volumes.empty:
            combined = counts
        else:
            combined = counts.merge(
                volumes,
                on=["profile", "cruise", "depth_bin"],
                how="outer",
                suffixes=("", "_vol"),
            )
            combined["depth_bin_start_dbar"] = combined["depth_bin_start_dbar"].fillna(
                combined["depth_bin_start_dbar_vol"]
            )
            combined["depth_bin_end_dbar"] = combined["depth_bin_end_dbar"].fillna(
                combined["depth_bin_end_dbar_vol"]
            )
            combined["sampled_volume_L"] = combined["sampled_volume_L"].fillna(
                combined["sampled_volume_L_vol"]
            )
            combined = combined.drop(
                columns=[
                    "depth_bin_start_dbar_vol",
                    "depth_bin_end_dbar_vol",
                    "sampled_volume_L_vol",
                ]
            )

        if "depth_bin_start_dbar" in combined.columns:
            combined["depth_bin_start_dbar"] = pd.to_numeric(
                combined["depth_bin_start_dbar"], errors="coerce"
            )
            combined = combined.sort_values("depth_bin_start_dbar")

        out_path = output_dir / f"{profile_name}_abundance_biovolume_by_depth.csv"
        combined.to_csv(out_path, index=False)
        print(f"Saved abundances + volumes: {out_path}")

        plot_bin_step = args.depth_bin_step if args.depth_bin_step else 50.0
        plot_path = output_dir / f"{profile_name}_abundance_biovolume_by_depth.png"
        make_profile_plot(combined, raw_df, plot_path, plot_bin_step)

        if not counts.empty:
            counts_shallow = counts[counts["depth_bin_start_dbar"] < 110]
            if not counts_shallow.empty:
                volume_totals = (
                    counts_shallow[["profile", "cruise", "depth_bin", "sampled_volume_L"]]
                    .drop_duplicates()
                    .groupby(["profile", "cruise"], observed=True)["sampled_volume_L"]
                    .sum()
                    .reset_index()
                    .rename(columns={"sampled_volume_L": "total_sampled_volume_L"})
                )
                summary = (
                    counts_shallow.groupby(
                        ["profile", "cruise", "object_annotation_category"], observed=True
                    )
                    .agg(
                        count=("count", "sum"),
                        biovolume_mm3=("biovolume_mm3", "sum"),
                    )
                    .reset_index()
                    .merge(volume_totals, on=["profile", "cruise"], how="left")
                )
                summary["count_per_L"] = summary["count"] / summary["total_sampled_volume_L"]
                summary["biovolume_mm3_per_L"] = (
                    summary["biovolume_mm3"] / summary["total_sampled_volume_L"]
                )
                summary_records.append(summary)

    if summary_records:
        summary_df = pd.concat(summary_records, ignore_index=True)
        if not summary_df.empty:
            plot_cruise_summary(summary_df, profile_order, output_dir)


if __name__ == "__main__":
    main()